name: test
on: push
jobs:
  test:
    name: Test the template
    runs-on: ubuntu-latest
    container:
      image: debian:buster-backports
    steps:
      - name: Install tools
        run: |
          apt-get update
          apt-get install doxygen-gui doxygen-doc swig
          apt-get -t buster-backports install cmake-qt-gui cmake-doc clang-8 clang-8-doc libc++1-8 ninja-build sbt

      - name: Checkout code
        uses: actions/checkout@v2
