name: test
on: push
env:
  # name of the template instance
  INSTANCE_NAME: test-deploy

jobs:
  debian-10-test:
    name: Test on Debian 10
    runs-on: ubuntu-latest
    container:
      image: debian:buster-backports
      env:
        CC: /usr/bin/clang-8
        CXX: /usr/bin/clang++-8

    steps:
      - name: Install Linux tools
        run: |
          apt-get -qq update
          apt-get -qq -o=Dpkg::Use-Pty=0 install curl gnupg sudo tree

      - name: Install compilation tools
        run: |
          echo "deb https://dl.bintray.com/sbt/debian /" >/etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
          apt-get -qq update
          apt-get -qq -o=Dpkg::Use-Pty=0 install doxygen-gui doxygen-doc openjdk-11-jdk swig sbt
          apt-get -qq -o=Dpkg::Use-Pty=0 -t buster-backports install cmake-qt-gui cmake-doc clang-8 clang-8-doc libc++1-8 ninja-build

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instantiate the template
        run: |
          mkdir ../test
          cd ../test
          sbt -Dsbt.ci=true -Dsbt.supershell=false new file://"$GITHUB_WORKSPACE" --name=$INSTANCE_NAME --package=com.test

      - name: Run CMake build
        run: |
          cd ../test/$INSTANCE_NAME
          cmake -S src -B target/cmake -G Ninja
          cmake --build target/cmake
          (cd target/cmake; ctest -VV)

      - name: Let's see the files
        run: |
          cd ../test/$INSTANCE_NAME
          tree -h
