name: test
on: push
jobs:
  debian-10-test:
    name: Test on Debian 10
    runs-on: ubuntu-latest
    container:
      image: debian:buster-backports
    steps:
      - name: Install Linux tools
        run: |
          apt-get -qq -o=Dpkg::Use-Pty=0 update
          apt-get -qq install curl gnupg sudo tree

      - name: Install compilation tools
        run: |
          echo "deb https://dl.bintray.com/sbt/debian /" >/etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
          apt-get -qq -o=Dpkg::Use-Pty=0 update
          apt-get -qq install doxygen-gui doxygen-doc swig sbt
          apt-get -qq -t buster-backports install cmake-qt-gui cmake-doc clang-8 clang-8-doc libc++1-8 ninja-build

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CMake build
        run: |
          cmake -S src -B target/cmake -G Ninja
          cmake --build target/cmake

      - name: Let's see what's here
        run: tree -h
